title: "Deep Reinforcement Learning for my Game Enemy AI" 
# author: Daniil Karzanov
layout: post
theme: jekyll-theme-slate  

markdown: kramdown
kramdown:
  input: GFM          # Enables GitHub Flavored Markdown
  # syntax_highlighter_opts:
  #   line_numbers: true
